# [START gae_python37_cloudsql_config]
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: postgres
  CLOUD_SQL_PASSWORD: 12346
  CLOUD_SQL_DATABASE_NAME: guestbook
  CLOUD_SQL_CONNECTION_NAME: folk-dev-com-db:us-central1:myinstance2
# [END gae_python37_cloudsql_config]
